# Configuration file for Maxon EPOS3 drive
vendor_id: 0x000022D2
product_id: 0x00000301
#assign_activate: 0x0300 # DC Synch register
auto_fault_reset: false # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"
#sdo: # sdo data to be transferred at drive startup
#  - { index: 0x60C2, sub_index: 1, type: int8, value: 10 } # Set interpolation time for cyclic modes to 10 ms
#  - { index: 0x60C2, sub_index: 2, type: int8, value: -3 } # Set base 10-3s
rpdo: # RxPDO
  - index: 0x1600 # Receive PDO1 Mapping
    channels:
      - { index: 0x6040, sub_index: 0, type: uint16, command_interface: controlword, default: 0}  # Control Word
      - { index: 0x6060, sub_index: 0, type: int8, command_interface: modeOfOperation, default: 8}  # Mode of Operation
      - { index: 0x6071, sub_index: 0, type: int16, default: 0 } # Target Torque
      - { index: 0x607a, sub_index: 0, type: int32, command_interface: position, default: .nan, } # Target Position
      - { index: 0x60ff, sub_index: 0, type: int32, default: 0 } # Target Velocity
      - { index: 0x60b2, sub_index: 0, type: int16, default: 0 } # Torque Offset
      - { index: 0x2701, sub_index: 0, type: int32, default: 0 } # Tuning Command
  - index: 0x1601 # Receive PDO2 Mapping
    channels:
      - { index: 0x60fe, sub_index: 1, type: uint16, default: 0 } # Physical Outputs
      - { index: 0x60fe, sub_index: 2, type: uint16, default: 0 } # Bit Mask
  - index: 0x1602 # Receive PDO3 Mapping
    channels:
      - { index: 0x2703, sub_index: 0, type: uint16, default: 0 } # User MOSI
      - { index: 0x60b1, sub_index: 0, type: uint16, default: 0 } # Velocity Offset
tpdo: # TxPDO 
  - index: 0x1a00 # Transmit PDO1 Mapping
    channels:
      - { index: 0x6041, sub_index: 0, type: uint16, state_interface: statusword}  # Status Word
      - { index: 0x6061, sub_index: 0, type: int8 } # Mode of operation display
      - { index: 0x6064, sub_index: 0, type: int32, state_interface: position } # Position actual value
      - { index: 0x606c, sub_index: 0, type: int32, state_interface: velocity } # Velocity actual value
      - { index: 0x6077, sub_index: 0, type: int16, state_interface: effort } # Torque actual value
  - index: 0x1a01 # Transmit PDO2 Mapping
    channels:
      - { index: 0x2401, sub_index: 0, type: uint16 } # Analog Input 1
      - { index: 0x2402, sub_index: 0, type: uint16 } # Analog Input 2
      - { index: 0x2403, sub_index: 0, type: uint16 } # Analog Input 3
      - { index: 0x2404, sub_index: 0, type: uint16 } # Analog Input 4
      - { index: 0x2702, sub_index: 0, type: uint32 } # Tuning Status
  - index: 0x1a02 # Transmit PDO3 Mapping
    channels:
      - { index: 0x60fd, sub_index: 0, type: uint32 } # Digital Inputs
  - index: 0x1a03 # Transmit PDO4 Mapping
    channels:
      - { index: 0x2704, sub_index: 0, type: uint32 } # User MISO
      - { index: 0x20f0, sub_index: 0, type: uint32 } # Timestamp
      - { index: 0x60fc, sub_index: 0, type: uint32 } # Position Demand Internal Value
      - { index: 0x606b, sub_index: 0, type: uint32 } # Velocity Demand Value
      - { index: 0x6074, sub_index: 0, type: uint16 } # Torque Demand
