controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    drive_controller:
      type: ethercat_controllers/CiA402Controller

trajectory_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - joint_1

velocity_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
    joints:
      - joint_1

effort_controller:
  ros__parameters:
    command_interfaces:
      - effort
    state_interfaces:
      - effort
    joints:
      - joint_1

drive_controller:
  ros__parameters:
    joints:
      - joint_1
